apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./external-secret-operator
  - ./storage
  - ./cert-manager
  - ./seafile # TODO
  - ./vaultwarden
  - ./network # TODO
  - ./keycloak
  - .observability
  - ./media
  - ./ocis # TODO
  - ./vikunja
  - ./searxng
