apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/external-secret-operator
  - ../../base/storage
  - ../../base/cert-manager
  - ./seafile
  - ./vaultwarden
  - ./network
  - ../../base/keycloak
  - ../../base/observability
  - ../../base/media
