# Specific tasks for Radxa ROCK 5 ITX
- name: Install cpufrequtils
  ansible.builtin.apt:
    pkg:
      - cpufrequtils

- name: Set cpufrequtils
  block:
    - name: Enable option
      ansible.builtin.lineinfile:
        path: /etc/default/cpufrequtils
        search_string: "ENABLE"
        line: 'ENABLE="true"'
    - name: Restart service
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        enabled: true
        name: cpufrequtils
