apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: grafana-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: CLUSTER_NAME
      remoteRef:
        key: cluster-common
        property: cluster_name
    - secretKey: CLIENT_ID
      remoteRef:
        key: app-grafana-secrets
        property: client_id
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: app-grafana-secrets
        property: client_secret
    - secretKey: ADMIN_USER
      remoteRef:
        key: app-grafana-secrets
        property: admin_user
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: app-grafana-secrets
        property: admin_password
