apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: BOOTSTRAP_ADMIN_USERNAME
      remoteRef:
        key: app-keycloak-secrets
        property: bootstrap_admin_username
    - secretKey: BOOTSTRAP_ADMIN_PASSWORD
      remoteRef:
        key: app-keycloak-secrets
        property: bootstrap_admin_password
