apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/keycloak
  - ../network
  - es-keycloak-secrets.yml
  - es-keycloak-provisioning.yml
  - es-postgres-secrets.yml

replacements:
  - source:
      kind: ConfigMap
      name: cluster-routes-and-domains
      fieldPath: data.KEYCLOAK_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: keycloak
          namespace: identity
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: keycloak
          namespace: identity
        fieldPaths:
          - spec.tls.domains.0.main
  - source:
      kind: ConfigMap
      name: cluster-routes-and-domains
      fieldPath: data.KEYCLOAK_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: keycloak
          namespace: identity
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: ConfigMap
      name: cluster-routes-and-domains
      fieldPath: data.KEYCLOAK_REALM
    targets:
      - select:
          kind: Deployment
          name: keycloak
          namespace: identity
        fieldPaths:
          - spec.template.spec.containers.[name=keycloak-provisionner].env.[name=REALM].value
