apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser
  namespace: media
spec:
  secretName: domain-tls-filebrowser
  commonName: <FILEBROWSER_DOMAIN>
  dnsNames:
    - <FILEBROWSER_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
