apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: transmission
  namespace: media
spec:
  secretName: domain-tls-transmission
  commonName: <TRANSMISSION_DOMAIN>
  dnsNames:
    - <TRANSMISSION_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
