apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: transmission
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: <TRANSMISSION_MATCH>
      middlewares:
        - name: oidc-transmission
          namespace: media
      observability:
        accessLogs: true
        metrics: true
      services:
        - name: transmission
          namespace: media
          port: 80
  tls:
    secretName: domain-tls-transmission
    domains:
      - main: <TRANSMISSION_DOMAIN>
