apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/media
  - ../network
  - es-cluster-variables.yml
  - cm-filebrowser-config-tpl.yml
  - es-filebrowser-config.yml
  - es-traefik-middleware-oidc.yml

replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-routes-and-domains
      fieldPath: data.TRANSMISSION_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: transmission
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: transmission
        fieldPaths:
          - spec.tls.domains.0.main
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-routes-and-domains
      fieldPath: data.FILEBROWSER_DOMAIN
    targets:
      - select:
          kind: Certificate
          name: filebrowser
        fieldPaths:
          - spec.commonName
          - spec.dnsNames.0
      - select:
          kind: IngressRoute
          name: filebrowser
        fieldPaths:
          - spec.tls.domains.0.main
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-routes-and-domains
      fieldPath: data.TRANSMISSION_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: transmission
        fieldPaths:
          - spec.routes.0.match
  - source:
      kind: ConfigMap
      version: v1
      name: cluster-routes-and-domains
      fieldPath: data.FILEBROWSER_MATCH
    targets:
      - select:
          kind: IngressRoute
          name: filebrowser
        fieldPaths:
          - spec.routes.0.match
