apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: filebrowser
    newName: gtstef/filebrowser
    newTag: 1.0.1-stable-slim
  - name: internal-ca-loader
    newName: alpine/openssl
    newTag: "3.3.3"

resources:
  - certificate-filebrowser.yml
  - cm-filebrowser-config-tpl.yml
  - deploy-filebrowser.yml
  - es-filebrowser-config.yml
  - ingressroute-filebrowser.yml
  - svc-filebrowser.yml



