apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: searxng
    namespace: searxng
    files:
      - confs/settings.yml

images:
  - name: searxng
    newName: searxng/searxng
    newTag: "2026.1.30-ad42b553b"

resources:
  - certificate-searxng.yml
  - deploy-searxng.yml
  - ingressroute-searxng.yml
  - ns-searxng.yml
  - pvc-searxng.yml
  - svc-searxng.yml
