apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: observability
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        runAsUser: 61003
        runAsGroup: 61003
        fsGroup: 61003
      containers:
        - name: loki-reverse-proxy
          image: loki-reverse-proxy
          ports:
            - containerPort: 8080
              name: http-loki-auth
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: loki-config
              subPath: loki-reverse-proxy.conf
            - mountPath: /etc/nginx/.htaccess
              name: loki-secrets
              subPath: .HTACCESS
        - name: loki
          image: loki
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 200Mi
          env: []
          volumeMounts:
            - mountPath: /etc/loki/local-config.yaml
              name: loki-config
              subPath: loki-config.yaml
            - mountPath: /loki
              name: loki-pvc
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-pvc
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: loki-secrets
          secret:
            secretName: loki-secrets
          