apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: internal-ca-loader
    newName: alpine/openssl
    newTag: "3.3.3"
  - name: grafana
    newName: grafana/grafana
    newTag: "12.0.1"
  - name: loki
    newName: docker.io/grafana/loki
    newTag: "3.6.4"
  - name: loki-reverse-proxy
    newName: nginxinc/nginx-unprivileged
    newTag: "1.29-alpine3.22"
  - name: alloy
    newName: docker.io/grafana/alloy
    newTag: "v1.10.1"

resources:
  - certificate-observability.yml
  - clusterrole-cluster-monitor.yml
  - clusterrolebinding-cluster-monitor.yml
  - cm-grafana-config.yml
  - deploy-alloy.yml
  - deploy-grafana.yml
  - deploy-loki.yml
  - ingressroute-observability.yml
  - ns-observability.yml
  - pvc-grafana.yml
  - pvc-loki.yml
  - sa-alloy.yml
  - svc-grafana.yml
  - svc-loki.yml

configMapGenerator:
  - name: loki-config
    namespace: observability
    files:
      - confs/loki-config.yaml
      - confs/loki-reverse-proxy.conf
  - name: alloy-config
    namespace: observability
    files:
      - confs/config.alloy
  - name: grafana-datasources
    namespace: observability
    files:
      - confs/grafana-datasources/source-loki.yml
  - name: grafana-dashboards
    namespace: observability
    files:
      - confs/grafana-dashboards/default.yml
      - confs/grafana-dashboards/logs.json
