apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikunja
  namespace: vikunja
spec:
  secretName: domain-tls
  commonName: tasks.enki.sin
  dnsNames:
    - tasks.enki.sin
    - tasks.enki.sin:8443
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
