apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vikunja
  namespace: vikunja
spec:
  secretName: domain-tls
  commonName: <VIKUNJA_DOMAIN>
  dnsNames:
    - <VIKUNJA_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
