- name: Get technitium status
  ansible.builtin.systemd_service:
    name: technitium
  register: technitium_status

- name: Check that technitium is running
  ansible.builtin.assert:
    that: technitium_status['status']['ActiveState'] == 'active'
