- name: Set kernel parameter cgroup_memory
  ansible.builtin.lineinfile:
    regexp: ^((?!.*cgroup_memory).*)$
    path: /boot/firmware/current/cmdline.txt
    line: '\1 cgroup_memory=1'
    backrefs: yes

- name: Set kernel parameter cgroup_enable
  ansible.builtin.lineinfile:
    regexp: ^((?!.*cgroup_enable).*)$
    path: /boot/firmware/current/cmdline.txt
    line: '\1 cgroup_enable=memory cgroup_enable=cpuset'
    backrefs: yes
