apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-ocis-secrets
  namespace: ocis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: ocis-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: app-ocis-secrets
        property: admin_password