apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-config
  namespace: ocis
  annotations:
    defaultVolumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi