apiVersion: v1
kind: PersistentVolumeClaim # TODO: make it persistent 
metadata:
  name: ocis-data
  namespace: ocis
  annotations:
    defaultVolumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
