apiVersion: v1
kind: Service
metadata:
  name: ocis
  namespace: ocis
  labels:
    app: ocis
    namespace: ocis
spec:
  ports:
    - name: grpc
      port: 9142
      targetPort: 9142
    - name: api
      port: 9233
      targetPort: 9233
    - name: web
      port: 9200
      targetPort: 9200
  selector:
    app: ocis