- name: "Mount Partitions: Reload systemd daemon"
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Mount all volumes from /etc/fstab # noqa: command-instead-of-module
  ansible.builtin.shell:
    cmd: mount -a
    executable: /bin/sh
  changed_when: false
