apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns-external-secrets.yml
  - build.yml
  - css-bitwarden-fields.yml
  - css-bitwarden-files.yml
# Uncomment for manifest generation
#
# kustomize build -o base/external-secret-operator/build.yml --enable-helm ./base/external-secret-operator
#
#helmCharts:
#  - name: external-secrets
#    repo: https://charts.external-secrets.io
#    releaseName: helm-chart
#    namespace: external-secrets
#    version: 1.2.1

