apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: identity
spec:
  secretName: domain-tls
  commonName: identity.enki.sin:8443
  dnsNames:
    - identity.enki.sin:8443
    - identity.enki.sin
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
