apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
  namespace: identity
spec:
  secretName: domain-tls
  commonName: <KEYCLOAK_DOMAIN>
  dnsNames:
    - <KEYCLOAK_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
