apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-clusterissuer
  namespace: cert-manager
  labels:
    app.kubernetes.io/part-of: domovoy
spec:
  ca:
    secretName: ca-cluster
