apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secrets
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: searxng-secrets
    deletionPolicy: Delete
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: app-searxng-secrets
        property: secret_key
