apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  secretName: domain-tls
  commonName: <VAULTWARDEN_DOMAIN>
  dnsNames:
    - <VAULTWARDEN_DOMAIN>
  issuerRef:
    name: ca-clusterissuer
    kind: ClusterIssuer
