apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: vaultwarden
    newName: vaultwarden/server
    newTag: 1.35.2-alpine
  - name: bitwarden-cli
    newName: zar3bski/bitwarden-cli
    newTag: "2025.10.0"

resources:
  - certificate-vaultwarden.yml
  - deploy-vaultwarden.yml
  - ingressroute-vaultwarden.yml
  - ns-vaultwarden.yml
  - pvc-vaultwarden.yml
  - svc-vaultwarden.yml

