apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  enki.server: |
    # Include specific server zone
    enki.sin. {
      errors
      hosts {
        192.168.1.49 identity.enki.sin.
        fallthrough
      }
      forward . /etc/resolv.conf
    }