crds: 
  enabled: true
hostNetwork: true
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
deployment: 
  kind: DaemonSet

  initContainers:
    - name: ca-loader
      image: docker.io/traefik:v3.6.5
      command: 
        - "sh"
        - "-c"
        - "cat /etc/ssl/ca.crt >> /etc/ssl/certs-custom/ca-certificates.crt &&
           cat /etc/ssl/certs/ca-certificates.crt >> /etc/ssl/certs-custom/ca-certificates.crt"
      volumeMounts:
        - name: wildcard-domain-tls
          mountPath: /etc/ssl/ca.crt
          subPath: ca.crt
        - name: ca-certificates
          mountPath: /etc/ssl/certs-custom/
          
  additionalVolumes:
    - name: wildcard-domain-tls
      secret:
        secretName: wildcard-domain-tls
    - name: ca-certificates
      emptyDir: {}

additionalVolumeMounts:
  - name: ca-certificates
    mountPath: /etc/ssl/certs/ca-certificates.crt
    subPath: ca-certificates.crt

ports:
  web:
    port: 8080
  traefik:
    port: 4443
  websecure: 
    port: 8443
    tls:
      enabled: true
experimental:
  plugins:
    fail2ban:
      moduleName: github.com/tomMoulard/fail2ban
      version: v0.8.9
    traefikoidc:
      moduleName: github.com/lukaszraczylo/traefikoidc
      version: v0.8.17
logs:
  general:
    level: "INFO"
  access:
    enabled: true
    fields: 
      general:
        names: 
          StartUTC: drop
service:
  spec:
    externalTrafficPolicy: Local